#ifndef ZORASM_KW_H
#define ZORASM_KW_H

typedef enum {
  ZORASM_DATA_INT,
  ZORASM_DATA_STRING,
  ZORASM_DATA_FLOAT
} ZORASM_DATAKIND;

#define ZoraVM_KindAsStr(kind)  \
(kind == ZORASM_DATA_STRING ? "string" : \
 (kind == ZORASM_DATA_INT ? "integer" : \
  (kind == ZORASM_DATA_FLOAT ? "float" : "nil" )))

typedef enum {
  ZORASM_INST_STORE = 0,
  ZORASM_INST_LOAD,
  ZORASM_INST_PUSH,
  ZORASM_INST_POP,
  ZORASM_INST_DUP,
  ZORASM_INST_SWAP,
  ZORASM_INST_PRINT,
  ZORASM_INST_SCAN,
  ZORASM_INST_SIZEOF,
  ZORASM_INST_AND,
  ZORASM_INST_OR,
  ZORASM_INST_XOR,
  ZORASM_INST_NOT,
  ZORASM_INST_NEG,
  ZORASM_INST_SHL,
  ZORASM_INST_SHR,
  ZORASM_INST_ADD,
  ZORASM_INST_SUB,
  ZORASM_INST_MUL,
  ZORASM_INST_DIV,
  ZORASM_INST_MOD,
  ZORASM_INST_POW,
  ZORASM_INST_INC,
  ZORASM_INST_DEC,
  ZORASM_INST_EQ,
  ZORASM_INST_GT,
  ZORASM_INST_LT,
  ZORASM_INST_GTE,
  ZORASM_INST_LTE,
  ZORASM_INST_NEQ,
  ZORASM_INST_NGT,
  ZORASM_INST_NLT,
  ZORASM_INST_NGTE,
  ZORASM_INST_NLTE,
  ZORASM_INST_JMP,
  ZORASM_INST_JMPIF,
  ZORASM_INST_JMPIFN,
  ZORASM_INST_CALL,
  ZORASM_INST_CALLIF,
  ZORASM_INST_CALLIFN,
  ZORASM_INST_DUMP_STACK,
  ZORASM_INST_DUMP_MEM,
  ZORASM_INST_RET,
  ZORASM_INST_HALT,
} ZORASM_INST;

ZORASM_INST Zorasm_char_to_inst(char *s);


#endif
